import { NextResponse } from "next/server";

export async function GET() {
  const data = [
    {
      id: "1",
      name: "Brooklyn Simmons",
      employeeId: "124335111",
      department: "PM",
      designation: "Project Manager",
      type: "Office",
      status: "Permanent",
      imageUrl: "https://i.pravatar.cc/150?img=1",
    },
    {
      id: "2",
      name: "Darlene Robertson",
      employeeId: "345321231",
      department: "Design",
      designation: "UI/UX Designer",
      type: "Office",
      status: "Permanent",
      imageUrl: "https://i.pravatar.cc/150?img=2",
    },
    {
      id: "3",
      name: "Floyd Miles",
      employeeId: "987890345",
      department: "Development",
      designation: "PHP Developer",
      type: "Office",
      status: "Permanent",
      imageUrl: "https://i.pravatar.cc/150?img=3",
    },
    {
      id: "4",
      name: "Cody Fisher",
      employeeId: "453367122",
      department: "Sales",
      designation: "Sales Manager",
      type: "Office",
      status: "Permanent",
      imageUrl: "https://i.pravatar.cc/150?img=4",
    },
    {
      id: "5",
      name: "Dianne Russell",
      employeeId: "345321231",
      department: "Sales",
      designation: "BDM",
      type: "Remote",
      status: "Permanent",
      imageUrl: "https://i.pravatar.cc/150?img=5",
    },
    {
      id: "6",
      name: "Savannah Nguyen",
      employeeId: "453677881",
      department: "Design",
      designation: "Design Lead",
      type: "Office",
      status: "Permanent",
      imageUrl: "https://i.pravatar.cc/150?img=6",
    },
    {
      id: "7",
      name: "Jacob Jones",
      employeeId: "009918765",
      department: "Development",
      designation: "Python Developer",
      type: "Remote",
      status: "Permanent",
      imageUrl: "https://i.pravatar.cc/150?img=7",
    },
    {
      id: "8",
      name: "Marvin McKinney",
      employeeId: "238870122",
      department: "Development",
      designation: "Sr. UI Developer",
      type: "Remote",
      status: "Permanent",
      imageUrl: "https://i.pravatar.cc/150?img=8",
    },
    {
      id: "9",
      name: "Kristin Watson",
      employeeId: "43540099",
      department: "HR",
      designation: "HR Executive",
      type: "Office",
      status: "Permanent",
      imageUrl: "https://i.pravatar.cc/150?img=9",
    },
  ];
  return NextResponse.json(data);
}
